### ISSUE TITLE
Timeout on MPD socket

### ISSUE THREAD

**Issue by fliiiix** [radio-pi/python-websocket-backend#1]
There is still a possibility that the connection to the mpd socket fails after a long run time.

```
2017-04-16T16:57:07+0000 [_GenericHTTPChannelProtocol,2,192.168.XXX.XXX] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/local/src/radiopi/env/local/lib/python2.7/site-packages/twisted/web/http.py", line 1442, in dataReceived
	    finishCallback(data[contentLength:])
	  File "/usr/local/src/radiopi/env/local/lib/python2.7/site-packages/twisted/web/http.py", line 1768, in _finishRequestBody
	    self.allContentReceived()
	  File "/usr/local/src/radiopi/env/local/lib/python2.7/site-packages/twisted/web/http.py", line 1845, in allContentReceived
	    req.requestReceived(command, path, version)
	  File "/usr/local/src/radiopi/env/local/lib/python2.7/site-packages/twisted/web/http.py", line 766, in requestReceived
	    self.process()
	--- <exception caught here> ---
	  File "/usr/local/src/radiopi/env/local/lib/python2.7/site-packages/twisted/web/server.py", line 190, in process
	    self.render(resrc)
	  File "/usr/local/src/radiopi/env/local/lib/python2.7/site-packages/twisted/web/server.py", line 241, in render
	    body = resrc.render(self)
	  File "/usr/local/src/radiopi/env/local/lib/python2.7/site-packages/twisted/web/resource.py", line 250, in render
	    return m(request)
	  File "./api.py", line 26, in render_POST
	    PLAYER.play(data['url'])
	  File "./backend/MusicPlayerDaemon.py", line 15, in play
	    self.__client_alive()
	  File "./backend/MusicPlayerDaemon.py", line 37, in __client_alive
	    self.client.ping()
	  File "/usr/local/src/radiopi/env/local/lib/python2.7/site-packages/mpd.py", line 629, in decorator
	    return wrapper(self, name, args, bound_decorator(self, returnValue))
	  File "/usr/local/src/radiopi/env/local/lib/python2.7/site-packages/mpd.py", line 252, in _execute
	    self._write_command(command, args)
	  File "/usr/local/src/radiopi/env/local/lib/python2.7/site-packages/mpd.py", line 279, in _write_command
	    self._write_line(" ".join(parts))
	  File "/usr/local/src/radiopi/env/local/lib/python2.7/site-packages/mpd.py", line 259, in _write_line
	    self._wfile.flush()
	  File "/usr/lib/python2.7/socket.py", line 303, in flush
	    self._sock.sendall(view[write_offset:write_offset+buffer_size])
	socket.error: [Errno 32] Broken pipe
```

**Comment by fliiiix** [comment]
Try this: https://github.com/Mic92/python-mpd2/issues/64

**Comment by fliiiix** [comment]
fixed
